name: Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
      working-directory: myFitness/ClientApp
    - run: npm run build --if-present
      working-directory: myFitness/ClientApp
      env:
        CI: false

  build-dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build myFitness.sln --no-restore

  test-dotnet:
    runs-on: ubuntu-latest
    needs: [build-react, build-dotnet]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Unit test
      run: dotnet test

  build-docker:
    runs-on: ubuntu-latest
    needs: [build-react, build-dotnet]

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: docker build -t myfitness .
    - name: Push Docker image
      run: docker push myfitness

  build-container:
    runs-on: ubuntu-latest
    needs: [build-docker]

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Pull Docker image
      run: docker pull myfitness
    - name: Build Docker container
      run: docker run -d --name myfitnessapp -p 4000:5000 myfitness
