name: Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-react:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
      working-directory: myFitness/ClientApp
    - run: npm run build --if-present
      working-directory: myFitness/ClientApp
      env:
        CI: false
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build myFitness.sln --no-restore
    - name: Build
      run: dotnet run
      working-directory: myFitness/
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

  test-dotnet:
    runs-on: ubuntu-latest
    needs: [build-react, build-dotnet]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Unit test
      run: dotnet test
    
    # Include later
    # - run: npm test
    #   working-directory: myFitness/ClientApp
