name: Build CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
        working-directory: myFitness/ClientApp
      - run: npm run build --if-present
        working-directory: myFitness/ClientApp
        env:
          CI: false

  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build myFitness.sln --no-restore

  test-dotnet:
    runs-on: ubuntu-latest
    needs: [build-react, build-dotnet]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Unit test
        run: dotnet test

  build-docker:
    runs-on: ubuntu-latest
    needs: [build-react, build-dotnet]

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY_NAME }} -f ./myFitness/dockerfile .
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REPOSITORY_NAME }}

  build-container:
    runs-on: ubuntu-latest
    needs: [build-docker]

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_REPOSITORY_NAME }}
      - name: Build Docker container
        run: docker run -d --name myfitnessapp -p 4000:5050 ${{ secrets.DOCKER_REPOSITORY_NAME }}
  aws-deploy:
    runs-on: ubuntu-latest
    needs: [build-container]
    steps:
      - uses: actions/checkout@v2
      - name: Start EC2 instance
        run: aws ec2 start-instances --instance-ids i-05196afce046ef6b7
      - name: Wait for EC2 instance to be running
        run: aws ec2 wait instance-running --instance-ids i-05196afce046ef6b7
      - name: Get Elastic IP address of the instance
        id: get-elastic-ip
        run: |
          elastic_ip=$(aws ec2 describe-instances --instance-ids i-05196afce046ef6b7 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          echo "Elastic IP: $elastic_ip"
          echo "::set-output name=elastic_ip::$elastic_ip"
      - name: Decode SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/myfitness.pem
          chmod 600 ~/.ssh/myfitness.pem
      - name: Transfer Docker image to EC2
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/myfitness.pem myfitness.tar ec2-user@${{ steps.get-elastic-ip.outputs.elastic_ip }}:/home/ec2-user/
      - name: Load Docker image and run container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/myfitness.pem ec2-user@${{ steps.get-elastic-ip.outputs.elastic_ip }} \
          "docker load -i myfitness.tar && docker run -d -p 5050:5050 ${{ secrets.DOCKER_REPOSITORY_NAME }}:latest"
      - name: Cleanup after deployment
        run: aws ec2 stop-instances --instance-ids i-05196afce046ef6b7